### PR TITLE
Weeb central dynamic chapter name

### LINKED ISSUE #545: [Tranga broke]: [WeebCentral] Manga with odd naming scheme for chapters
### What is broken?

Some manga on WeebCentral  have odd naming sceme for the chapters like manga Rooming with a gamer gal. it has SERVER instead of CHAPTER. so it breaks the API for downloading the manga chapters ex : from logs 

"2026-01-22 04:33:03,467 [30] WARN  WeebCentral - Unknown chapter format: Server 13

2026-01-22 04:33:03,467 [30] WARN  WeebCentral - Unknown chapter format: Server 12

2026-01-22 04:33:03,467 [30] WARN  WeebCentral - Unknown chapter format: Server 11

2026-01-22 04:33:03,467 [30] WARN  WeebCentral - Unknown chapter format: Server 10

2026-01-22 04:33:03,467 [30] WARN  WeebCentral - Unknown chapter format: Server 9

2026-01-22 04:33:03,467 [30] WARN  WeebCentral - Unknown chapter format: Server 8

2026-01-22 04:33:03,467 [30] WARN  WeebCentral - Unknown chapter format: Server 7

2026-01-22 04:33:03,467 [30] WARN  WeebCentral - Unknown chapter format: Server 6

2026-01-22 04:33:03,467 [30] WARN  WeebCentral - Unknown chapter format: Server 5

2026-01-22 04:33:03,467 [30] WARN  WeebCentral - Unknown chapter format: Server 4

2026-01-22 04:33:03,467 [30] WARN  WeebCentral - Unknown chapter format: Server 3

2026-01-22 04:33:03,467 [30] WARN  WeebCentral - Unknown chapter format: Server 2

2026-01-22 04:33:03,467 [30] WARN  WeebCentral - Unknown chapter format: Server 1

"

https://weebcentral.com/series/01J76XYGW2C9YGX7E0NAHV6DGK

Manga on site for reference. 

### Log-output

```console

```

### Tranga version

```console

```

### Additional stuff

_No response_

### PR DESCRIPTION
**Pull request by TheyCallMeTravis**
chapterNumber now grabs "chapter" or "ch" number; if none are found, uses last number in string. (fixes #545)

Added volume/season variable when exists; will be needed for #543.

### CODE REVIEW

**Comment by FelixFeuerigel** [comment]
I have been looking at this too and came up with:
```c#
string href = node.GetAttributeValue("href", "").Trim();
string text = node.InnerText.Trim();

Log.Debug($"Got chapter with Name text: '{text}'"); //TODO: remove

string chapterNumber;
int? volumeNumber = null;
string? chapterTitle = null;

// Try to detect volume and chapter numbers.
// Group 1: volume numbers after 'S' or 'Vol.'
// Group 2: the last number with dot seperation like 1.1 or 1.12.4
// Only use lines that have a number and at least one other character.
// This is needed because the text also contains additional garbage text.
// If the detection breaks, maybe only allowing lines with the chapter number at the very end helps.
Regex titleRegex = new Regex(@"[^\r\n]*?(?:(?:s|vol)\.? ?(\d)+[ ][^\r\n]*?)?(?<=[^\d\s\.][^\r\n]*)(\d+(?:[\.]\d+)*)[^\d\r\n]*$", RegexOptions.IgnoreCase|RegexOptions.Multiline);

// Selection is the whole line the title was found in.
// Group 1 is volume/season integer, if detected.
// Group 2 is the chapter number / the last number in the title with the format: \d+(\.\d+)*
Match match = titleRegex.Match(text);

if (match.Success)
{
    chapterTitle = match.Value.Trim(); // Use the whole line as title but remove whitespace
    Log.Debug($"Selected title: '{chapterTitle}'"); //TODO: remove

    chapterNumber = match.Groups[2].Value;

    // Set the volumeNumber to Group 1 of regex if it has a result
    if (match.Groups[1].Success)
    {
        int detectedVolumeNumber;
        if (int.TryParse(match.Groups[1].Value, out detectedVolumeNumber))
        {
            volumeNumber = detectedVolumeNumber;
        }
        else
        {
            Log.Warn($"Unknown volume format: {match.Groups[1].Value}");
        }   
    }
}
else
{
    // fallback for specials
    chapterNumber = "0";
    Log.Warn($"Unknown chapter format: {text}");
}

Chapter ch = new(manga.Obj, chapterNumber, volumeNumber, chapterTitle);
string chapterIdOnSite = new Uri(href).Segments.Last();
string canonicalChapterUrl = $"https://weebcentral.com/chapters/{chapterIdOnSite}";
MangaConnectorId<Chapter> mcId = new(ch, this, chapterIdOnSite, canonicalChapterUrl);
ch.MangaConnectorIds.Add(mcId);
chapters.Add((ch, mcId));
```

This also tries to find a volume number and a title, but if `SelectSingleNode(".//span[@class='']")` works, then this is probably unnecessarily complex.

**Comment by FelixFeuerigel** [comment]
A collection of all the chapter names if found so far (converted to lowecase):
```
s3 - chapter 61
episode 22.5
mag version 222
ch. 574
vol. 1 ch. 3
server 117
creature 16
e 56
# 32
sword 15
vol. 5.2
depth: 172
s2 - episode 109
yotaro odyssey: 23
session 14
volume 12.5
island waves 8
lecture 43
s3 - chapter 0
confession 36.5
appeal 18
```

@TheyCallMeTravis does your solution work if 'volume' is used for chapter numbering like 'vol. 5.2' or 'volume 12.5' ?

**Comment by TheyCallMeTravis** [comment]
@FelixFeuerigel Hmm, the `chapterNumber` variable will work fine, but good catch, it will probably fail when it tries to parse the `2.5` into an integer for `volumeNumber`. Drop a link to that specific example you found and I can test further.
Realistically I should remove the decimal portion of the regex for `volumeNumber` anyways, so it only grabs a whole number.

File: API/MangaConnectors/WeebCentral.cs [hunk 1]
```diff
@@ -211,24 +211,39 @@ public override (Chapter, MangaConnectorId<Chapter>)[] GetChapters(MangaConnecto
         foreach (HtmlNode node in chapterNodes)
         {
             string href = node.GetAttributeValue("href", "").Trim();
-            string text = node.InnerText.Trim();
-
-            // Get chapter number - supports decimals and multiple WeebCentral chapter naming schemes
+			string text = node.SelectSingleNode(".//span[@class='']").InnerText.Trim();
```
Comment (C9Glax) [inline API/MangaConnectors/WeebCentral.cs]: I think this wont work right now, there is 2 `span` nodes:
image
So you need to specify the class

File: API/MangaConnectors/WeebCentral.cs [hunk 2]
```diff
@@ -211,24 +211,39 @@ public override (Chapter, MangaConnectorId<Chapter>)[] GetChapters(MangaConnecto
...
+				{
+					chapterNumber = numberMatches[numberMatches.Count - 1].Value;
+					Log.Warn($"Unknown chapter format detected. Using last number in string: {chapterNumber}");
+				}
+				else
+				{
+					//fallback for everything else
+					chapterNumber = "0";
+					Log.Warn($"Unknown chapter format: {text}");
+				}
```
Comment (C9Glax) [inline API/MangaConnectors/WeebCentral.cs]: I think we shouldn't use a default "0" and instead only log the warning and ignoring the entry (not adding it to the return)

**Comment by FelixFeuerigel** [comment]
> @FelixFeuerigel Hmm, the `chapterNumber` variable will work fine, but good catch, it will probably fail when it tries to parse the `2.5` into an integer for `volumeNumber`. Drop a link to that specific example you found and I can test further. Realistically I should remove the decimal portion of the regex for `volumeNumber` anyways, so it only grabs a whole number.

For finding examples I just spam the random button on WeebCentral.
The one that came up just now is: https://weebcentral.com/series/01J76XYE2B1KWNQWVMDH0GKTG5
For 'volumeNumber', the problem that I meant is not the decimal point, but that the number behind 'volume' can also be the chapter number.

**Comment by C9Glax** [comment]
> For 'volumeNumber', the problem that I meant is not the decimal point, but that the number behind 'volume' can also be the chapter number.

Those cases would have the problem that the volume Regex captures the number as volume number, and the chapter Regex would then fall back to that number as the chapter number.
Which in itself isn't all that bad tbh. Maybe not the intention, but the result would be "okay".

**Comment by C9Glax** [comment]
If you replace the `var` with explicit types I think this will be fine.
@FelixFeuerigel Can we split the work on volume-numbers being included in the key to a separate PR?

**Comment by TheyCallMeTravis** [comment]
@C9Glax Word, this should be good to go now.
